//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFormat.Tests.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocTest1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocTest1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartFormat.Tests.Localization.LocTest1", typeof(LocTest1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {} item.
        /// </summary>
        public static string ___item {
            get {
                return ResourceManager.GetString("{} item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {} items.
        /// </summary>
        public static string ___items {
            get {
                return ResourceManager.GetString("{} items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1:#,#} inhabitants.
        /// </summary>
        public static string _0__has__1______inhabitants {
            get {
                return ResourceManager.GetString("{0} has {1:#,#} inhabitants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has {:#,#} inhabitants.
        /// </summary>
        public static string has________inhabitants {
            get {
                return ResourceManager.GetString("has {:#,#} inhabitants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entry only exists in the invariant culture resource.
        /// </summary>
        public static string OnlyExistForInvariantCulture {
            get {
                return ResourceManager.GetString("OnlyExistForInvariantCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We translate text.
        /// </summary>
        public static string WeTranslateText {
            get {
                return ResourceManager.GetString("WeTranslateText", resourceCulture);
            }
        }
    }
}
